### ISSUE TITLE
Crashes on trying to view a document

### ISSUE THREAD

**Issue by Munchotaur** [solderpunk/VF-1#14]
VF-1 looks great so far, but after sucessfully navigating a menu (for example SDF.org or my local gopher server) it crashes every time I try to view a text document listed in a menu.

Here is a sample error:

```Traceback (most recent call last):
  File "/usr/lib/python3.4/cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'GopherClient' object has no attribute 'do_2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/vf1", line 9, in <module>
    load_entry_point('VF-1==0.0.2', 'console_scripts', 'vf1')()
  File "/usr/local/lib/python3.4/dist-packages/vf1.py", line 496, in main
    gc.cmdloop()
  File "/usr/lib/python3.4/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.4/cmd.py", line 216, in onecmd
    return self.default(line)
  File "/usr/local/lib/python3.4/dist-packages/vf1.py", line 252, in default
    self._go_to_gi(gi)
  File "/usr/local/lib/python3.4/dist-packages/vf1.py", line 156, in _go_to_gi
    subprocess.run(shlex.split(cmd_str % tmpf.name))
AttributeError: 'module' object has no attribute 'run'
```
I installed VF-1 using pip3. My system runs Linux Mint 17.3.

I see the same error whether I type (for example) '2' or 'go 2'.

Please let me know if there's anything I can to to help by pinning down the cause further.

**Comment by solderpunk** [comment]
Thanks very much for your bug report!  It looks to me like this problem is caused by your version of Python (3.4).  VF-1 uses the `subprocess.run`  function, which was only introduced in Python 3.5, so it will currently only work with 3.5 and above.  Sorry about this, I didn't realise at the time I was relying on such new functionality!  I know people are often stuck using older versions on Python on machines where they can't upgrade for whatever reason (I've been there myself) and I like to support older versions were feasible.

The good news is that it looks like it will be very easy to replace this with the older `subprocess.call` function, so then it should work fine on Python 3.4.  I will try to get around to this soon.

In the meantime, if you *are* able to upgrade your Python installation, this will probably solve the problem immediately.

**Comment by Munchotaur** [comment]
Thanks for the information. I'm reluctant to upgrade from "distro current" for my Mint laptop, in case it breaks anything else. However I can confirm that VF-1 works properly on FreeBSD 11 with Python 3.6. I'll use that for testing for the moment.

Happy to test again under Python 3.4 when you have time to revert to `subprocess.call`.

**Comment by solderpunk** [comment]
Okay, I have just pushed version 0.0.3 to PyPi which uses `subprocess.call`.  Can you please do a `pip3 install --upgrade VF-1` on your Mint machine and see if the problem is solved?

**Comment by solderpunk** [comment]
I'm going to assume this is fixed and close the issue, if you still have this problem with the latest version of VF-1 please open a new issue.

**Comment by Munchotaur** [comment]
Seems to be working now. Sorry for the delay in testing.

**Comment by solderpunk** [comment]
No problem, glad it works!
